http:
  middlewares:
    # Global service registry middleware
    service-registry:
      headers:
        customRequestHeaders:
          X-Service-Registry: "true"
    
    # Service-specific middlewares for rewriting paths
    document-service-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/documents"
    
    llm-service-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/llm"
    
    query-service-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/query"
          
    doc-processor-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/document-processor"

  # Define service registry
  services:
    service-registry:
      loadBalancer:
        passHostHeader: true