# Traefik Dynamic Configuration

http:
  middlewares:
    # Global service registry middleware
    service-registry:
      headers:
        customRequestHeaders:
          X-Service-Registry: "true"
    
    # Service-specific middlewares for rewriting paths
    document-service-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/documents"
    
    llm-service-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/llm"
    
    query-service-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/query"
          
    doc-processor-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/document-processor"
    
    minio-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/storage"

  # CORS configuration for all services
  middlewares:
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "*"  # For development - restrict in production
        accessControlMaxAge: 100
        addVaryHeader: true
