global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    metric_relabel_configs:
      - source_labels: [service_name]
        target_label: service

  - job_name: 'document-service'
    static_configs:
      - targets: ['document-service:8000']
    metrics_path: '/metrics'

  - job_name: 'query-service'
    static_configs:
      - targets: ['query-service:8000']
    metrics_path: '/metrics'

  - job_name: 'llm-service'
    static_configs:
      - targets: ['llm-service:8000']
    metrics_path: '/metrics'

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9308']  # Kafka Prometheus metrics exporter

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']  # MongoDB Prometheus metrics exporter
