name: LLM Service CI

on:
  push:
    branches: [ main ]
    paths:
      - 'microservices/llm-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'microservices/llm-service/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        cd microservices/llm-service
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-cov httpx
        pip install -r app/requirements.txt
        
    - name: Run unit tests
      run: |
        cd microservices/llm-service
        PYTHONPATH=. pytest tests/unit -v --cov=app --cov-report=xml
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./microservices/llm-service/coverage.xml
        fail_ci_if_error: false
        
  docker:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: ./microservices/llm-service/app
        file: ./microservices/llm-service/app/Dockerfile
        push: false
        load: true
        tags: llm-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Test docker image
      run: |
        docker run --rm llm-service:latest --version
