version: '3.8'

# Docker compose file for testing the metadata extraction flow
services:
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
  
  llm-service:
    build: 
      context: ./llm-service
    ports:
      - "8001:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - MAX_CONCURRENT_METADATA_TASKS=5
      - OLLAMA_API_URL=http://ollama:11434
    volumes:
      - ./llm-service:/app
    depends_on:
      - kafka
      - ollama
  
  document-service:
    build: 
      context: ./document-service
    ports:
      - "8002:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - MONGO_URI=mongodb://mongo:27017/document_service
      - DOCUMENT_PROCESSOR_URL=http://document-processor:8080
    volumes:
      - ./document-service:/app
      - ./data/document_storage:/app/data/storage
    depends_on:
      - kafka
      - mongo
  
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    command: serve

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  # Document processor service for extracting text from documents
  document-processor:
    build:
      context: ./document-processor
    ports:
      - "8003:8080"
    volumes:
      - ./data/document_temp:/app/temp
